# Generated by Django 6.0.4 on 2026-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='time',
            field=models.CharField(blank=True, choices=[('scan', 'Scan'), ('agregador', 'Agregador')], help_text='Time do usuário. Vazio para admins (acesso transversal).', max_length=20, null=True),
        ),
    ]
