# Generated by Django 6.0.4 on 2026-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('admin', 'Administrador')], default='admin', help_text='Nível de acesso do usuário', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='time',
            field=models.CharField(blank=True, choices=[('scan', 'Scan'), ('agregador', 'Agregador')], help_text='Time do usuário. Vazio apenas para superuser.', max_length=20, null=True),
        ),
    ]
