# Generated by Django 6.0.4 on 2026-04-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('ongoing', 'Em andamento'), ('completed', 'Completo')], default='ongoing', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=1, max_digits=6)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='catalog.obra')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_url', models.CharField(max_length=500)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500)),
                ('ordem', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='catalog.capitulo')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='capitulo',
            index=models.Index(fields=['obra', 'ordem'], name='catalog_cap_obra_id_3b791b_idx'),
        ),
        migrations.AddIndex(
            model_name='pagina',
            index=models.Index(fields=['capitulo'], name='catalog_pag_capitul_6a8383_idx'),
        ),
    ]
