# Generated by Django 6.0.4 on 2026-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='metadata',
        ),
        migrations.AddField(
            model_name='obra',
            name='capa_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='obra',
            name='sinopse',
            field=models.TextField(blank=True),
        ),
    ]
