# Generated by Django 6.0.4 on 2026-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_obra_metadata_obra_capa_url_obra_sinopse'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='fonte',
            field=models.CharField(choices=[('scan', 'Scan'), ('agregador', 'Agregador')], default='scan', max_length=20),
        ),
    ]
