# Generated by Django 6.0.4 on 2026-06-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_obra_idioma_favorito_historicoleitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='tipo_obra',
            field=models.CharField(choices=[('manga', 'Mangá/Manhwa'), ('novel', 'Light Novel')], default='manga', max_length=10),
        ),
    ]
