# Generated by Django 6.0.4 on 2026-06-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_tipo_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='tipo_obra',
            field=models.CharField(choices=[('manga', 'Mangá'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua'), ('novel', 'Light Novel')], default='manga', max_length=10),
        ),
    ]
