# Generated by Django 6.0.4 on 2026-06-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_update_tipo_obra_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='conteudo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
