# Generated by Django 6.0.4 on 2026-07-09 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_lista_leitura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='listaleitura',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorito',
            name='fonte',
            field=models.CharField(choices=[('scan', 'Scan'), ('agregador', 'Agregador')], db_index=True, default='scan', max_length=20),
        ),
        migrations.AddField(
            model_name='listaleitura',
            name='fonte',
            field=models.CharField(choices=[('scan', 'Scan'), ('agregador', 'Agregador')], db_index=True, default='scan', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'obra', 'fonte')},
        ),
        migrations.AlterUniqueTogether(
            name='listaleitura',
            unique_together={('usuario', 'obra', 'fonte')},
        ),
    ]
