# Generated by Django 6.0.4 on 2026-07-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_fonte_to_favorito_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaleitura',
            name='tipo',
            field=models.CharField(choices=[('reading', 'Lendo'), ('plan', 'Planejado'), ('completed', 'Concluído'), ('paused', 'Pausado')], default='reading', max_length=10),
        ),
    ]
