# Generated by Django 6.0.4 on 2026-07-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_add_paused_to_lista_leitura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='autor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='obra',
            name='capa_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='obra',
            name='sinopse',
            field=models.TextField(blank=True, default=''),
        ),
    ]
