# Generated by Django 6.0.4 on 2026-07-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_obra_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
