# Generated by Django 6.0.4 on 2026-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_change_data_publicacao_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo_obra',
            field=models.CharField(choices=[('manga', 'Mangá'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua'), ('novel', 'Light Novel')], default='manga', max_length=20),
        ),
    ]
