# Generated by Django 6.0.4 on 2026-08-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_increase_slug_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='tipo_obra',
            field=models.CharField(choices=[('manga', 'Mangá'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua'), ('novel', 'Novel'), ('light_novel', 'Light Novel'), ('webtoon', 'Webtoon'), ('unknown', 'Desconhecido')], default='manga', max_length=20),
        ),
    ]
